title: "Brenda Laime — ePortfolio"
description: "E-portfolio for OM 620 — Fall 2025"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

logo: /assets/img/logo.png

author:
  name: "Brenda Laime Jalil"
  avatar: "/assets/img/brenda-headshot-180.png"
  bio: "Project Administrator · Professional Racquetball Player · Aspiring Entrepreneur"
  location: "San Diego, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/brendalaime"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/"   # put your profile URL

header_pages:
 - projects.md

