title: "Brenda Laime — ePortfolio"
description: "E-portfolio for OM 620 — Fall 2025"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

logo: /assets/img/logo.jpg

author:
  name: "Brenda Laime Jalil"
  avatar: "/assets/img/logo.jpg"
  bio: "Project Administrator · Professional Racquetball Player · Aspiring Entrepreneur"
  location: "San Diego, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/brendalaime"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/"   # put your profile URL

# Adds a top navigation link to Projects if you create projects.md
header_pages:
  - projects.md
